name: CD Pipeline

on:
  workflow_run:
    workflows: ["CD Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: aws-ec2

    steps:
      - name: Pull Docker image from Docker Hub
        run: sudo docker pull henrydev4/nodejs-app:latest

      - name: Delete old container
        run: sudo docker rm -f nodejs-app-container || true

      - name: Run Docker container
        run: sudo docker run -d -p 5000:5000 --name nodejs-app-container henrydev4/nodejs-app:latest
