name: CICD

on:
  push:
    branches: [cicd-docker-ec2]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build Docker image
        run: docker build -t henrydev4/nodejs-app .

      - name: Publish Docker image to Docker Hub
        run: docker push henrydev4/nodejs-app:latest

  deploy:
    needs: build
    runs-on: aws-ec2 
    steps:
      - name: Pull Docker image from Docker Hub
        run: docker pull henrydev4/nodejs-app:latest

      - name: Delete old container
        run: docker rm -f nodejs-app-container || true

      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name nodejs-app-container henrydev4/nodejs-app:latest
