name: CICD

on:
  push:
    branches: [cicd-docker-ec2]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: docker build -t integrationdev/nodejs-app .

      - name: Publish Docker image to Docker Hub
        run: docker push integrationdev/nodejs-app:latest

  deploy: 
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Docker image from Docker Hub
        run: docker pull integrationdev/nodejs-app:latest

      - name: Delete old container
        run: docker rm -f nodejs-app-container || true

      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name nodejs-app-container integrationdev/nodejs-app:latest
