name: CICD

on:
  push:
    branches: [cicd-docker-ec2]
    
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to docker hub
        uses: docker login -u username -p password
        with:
          node-version: 16.x
      - name: Install Dependencies
        run : npm install
      - name: Test Project
        run: npm test
